service: todoAwsApi
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: oscar.mattsson
  region: eu-north-1
  iam:
    role: arn:aws:iam::785567638763:role/lecture-role

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  getTodo:
    handler: functions/getTodo/index.handler
    events:
      - httpApi:
          path: "/api/todos"
          method: GET
  postTodo:
    handler: functions/postTodo/index.handler
    events:
      - httpApi:
          path: "/api/todos"
          method: POST
  updateTodo:
    handler: functions/updateTodo/index.handler
    events:
      - httpApi:
          path: "/api/todos/{id}"
          method: PUT
  deleteTodo:
    handler: functions/deleteTodo/index.handler
    events:
      - httpApi:
          path: "/api/todos/{id}"
          method: DELETE

resources:
  Resources:
    todosDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todos-db
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
